version: '3.8'
services:
  app:
    build:
      context: .
    container_name: mercury_app
    env_file: ./.env
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mercury_db
    environment:
      MYSQL_HOST: mercury_db

  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: mercury_db
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=$MYSQL_DATABASE
      - PMA_USER=$MYSQL_USER
      - PMA_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT
    links:
      - mercury_db
    volumes:
      - /sessions

volumes:
  mysql:
  mysql_config:
